version: '3.8'

services:
  callcenter-server:
    build: 
      context: ./server
    container_name: callcenter-server
    networks:
      - callcenter-network
    ports:
      - "5678:5678"
    tty: true
    stdin_open: true

  callcenter-client:
    build:
      context: ./client
    container_name: callcenter-client
    depends_on:
      - callcenter-server
    networks:
      - callcenter-network
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1

networks:
  callcenter-network:
    driver: bridge
