
services:
  callcenter-server:
    build: ./server
    ports:
      - "5678:5678"
    networks:
      - callcenter-network
    container_name: callcenter-server
    
  callcenter-client:
    build: ./client
    depends_on:
      - callcenter-server
    networks:
      - callcenter-network
    container_name: callcenter-client
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1

networks:
  callcenter-network:
    driver: bridge